version: '3.4'

services:
  dockerdj:
    image: dockerdj
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000 # For frontend 
      - 8000:8000
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: db
      DB_PASSWORD: 123123 # LocalPassword

    volumes:
      - ..:/workspace
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    links: 
      - db

  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123123 # LocalPassword