version: '3.4'

services:
  backend_django:
    image: backend_django
    build:
      context: .
      dockerfile: ../backend/Dockerfile
    ports:
      - 8000:8000
    environment:
      # DATABASE_URL: sqlite:///db.sqlite3 # in case sqlite
      DB_ENGINE: django.db.backends.postgresql
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: db
      
      DB_PASSWORD: 123123 # LocalPassword
      ALLOWED_HOSTS: 127.0.0.1, localhost


    volumes:
      - ..:/workspace
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    links: 
      - postgresdb

  postgresdb:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432      
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data

